//types proyectos
export const FORMULARIO_PROYECTO = 'FORMULARIO_PROYECTO';
export const OBTENER_PROYECTOS = 'OBTENER_PROYECTOS';
export const AGREGAR_PROYECTO = 'AGREGAR_PROYECTO';
export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';
export const PROYECTO_ACTUAL = 'PROYECTO_ACTUAL';

//types tareas
export const OBTENER_TAREAS = 'OBTENER_TAREAS';
export const OBENTER_TAREAS_PROYECTO = 'OBTENER_TAREAS_POR_PROYECTO';
export const AGREGAR_TAREA = 'AGREGAR_TAREA';
export const VALIDAR_FORMULARIO_TAREA = 'VALIDAR_FORMULARIO_TAREA';
